tasks:
  - before: platformio upgrade
  - command: |
      platformio run -e esp32dev_qemu
      platformio run -t buildfs -e esp32dev_qemu
      platformio run -t qemu-image -e esp32dev_qemu

image:
  file: .gitpod.Dockerfile

vscode:
  extensions:
    - Atishay-Jain.All-Autocomplete
    - esbenp.prettier-vscode
    - shardulm94.trailing-spaces
    - ritwickdey.LiveServer
    - webfreak.debug
