tasks:
  - before: platformio upgrade
  - command: | 
    platformio run -e esp32dev
    platformio run --target buildfs --environment esp32dev 

image:
  file: .gitpod.Dockerfile

vscode:
  extensions:
    - Atishay-Jain.All-Autocomplete
    - esbenp.prettier-vscode
    - shardulm94.trailing-spaces
    - ritwickdey.LiveServer
