tasks:
  - command: |
      source /opt/esp/idf/export.sh
      source /opt/ros/galactic/local_setup.bash

image:
  file: .gitpod.Dockerfile

vscode:
  extensions:
    - espressif.esp-idf-extension
    - Atishay-Jain.All-Autocomplete
    - esbenp.prettier-vscode
    - shardulm94.trailing-spaces
    - robocorp.robotframework-lsp
