name: espidf CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        submodules: 'recursive'

    - name: Create build container
      run: docker build -t local - < .gitpod.Dockerfile

    - name: Build
      run: docker run -it -v $PWD:/srv -w/srv local echo "hello world"
