name: espidf CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
      with:
        submodules: 'recursive'
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    # So now you can use Actions' own caching!
    - name: Cache Docker layers
      uses: actions/cache@v3
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ hashFiles('.gitpod.Dockerfile') }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    - name: Create docker container
      uses: docker/build-push-action@v3
      with:
        file: .gitpod.Dockerfile
        tags: roboprog-dev-container
        push: false
        load: true
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,dest=/tmp/.buildx-cache

    - name: Build
      run: docker run -u 0 -v $PWD:/srv -w/srv roboprog-dev-container /bin/bash -c "source /opt/esp/idf/export.sh; source /opt/ros/galactic/local_setup.bash; idf.py build"

    - name: Build for Qemu
      run: docker run -u 0 -v $PWD:/srv -w/srv roboprog-dev-container /bin/bash -c "source /opt/esp/idf/export.sh; source /opt/ros/galactic/local_setup.bash; ./qemu_build.sh"

    - name: Run Tests
      run: docker run -u 0 -v $PWD:/srv -w/srv roboprog-dev-container /bin/bash -c "robot -d tests tests"

    - name: Upload Testresult
      uses: actions/upload-artifact@v3
      if: success() || failure()
      with:
        name: test-results
        path: |
          tests/
          !tests/*.robot
        retention-days: 30
