name: espidf CI

on: [push]

jobs:
  build:

    runs-on: espressif/idf

    steps:
    - name: Build
      run: idf.py build
#    - name: Build spiffs
#      run: pio run --target buildfs --environment esp32dev
    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: files-to-flash
        path: |
          ./main.bin
#          ./build/partitions.bin
#          ./build/piffs.bin
