name: espidf CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        submodules: 'recursive'

    - name: Create build container
      run: docker build -t roboprog-dev-container - < .gitpod.Dockerfile

    - name: Build
      run: docker run -u 0 -v $PWD:/srv -w/srv roboprog-dev-container /bin/bash -c "source /opt/esp/idf/export.sh; source /opt/ros/galactic/local_setup.bash; idf.py build"

    - name: Build for Qemu
      run: docker run -u 0 -v $PWD:/srv -w/srv roboprog-dev-container /bin/bash -c "source /opt/esp/idf/export.sh; source /opt/ros/galactic/local_setup.bash; ./qemu_build.sh"

    - name: Run Tests
      run: docker run -u 0 -v $PWD:/srv -w/srv roboprog-dev-container /bin/bash -c "robot -d tests tests"

    - name: Upload Testresult
      uses: actions/upload-artifact@v3
      if: success() || failure()
      with:
        name: test-results
        path: |
          tests/
          !tests/*.robot
        retention-days: 30
